### ISSUE TITLE
Select Experiments

### ISSUE THREAD

**Issue by fatolahzadeh** [pmlmodelling/nctoolkit#9] opened 2021-10-18 16:59 UTC
Some datasets I'm working on (ERA5) have multiple experiment versions, i.e., two or multiple values for each variable per time/coordinate, indicated as "expver". They are adding it to the 2021-present data. When dealing with a multiple file dataset, the pre-2021 files don't contain expver so calling the `merge_time` throws an error because of inconsistency.

**Comment by r4ecology** [comment] 2021-10-19 07:38
Can you clarify what the issue is? Do you want new functionality in `merge_time`?

**Comment by fatolahzadeh** [comment] 2021-10-24 01:00
I'm not sure it's a feature request or a bug. Some datasets (ERA5) have an extra channel (Experiment version), which results in two or more rows for a given time/location. So the workaround is to export the dataset into a dataframe and then filter the desired row using pandas.
The problem arises when those datasets come in multiple files. `merge_time` works when all files have the extra channel, but in some cases, like ERA5, the channel is something that is added some time along the dataset period. For instance, post-2020. So the channel exists on some files and doesn't on the rest. In this case, `merge_time` fails.

**Comment by r4ecology** [comment] 2021-11-03 11:09
This has now been added to the public release on conda and pypi, so I'll close the issue.

**Closed by r4ecology** 2021-11-03 11:09 UTC
