### ISSUE TITLE
Can't install the latest stable version on Linux (Ubuntu).

### ISSUE THREAD

**Issue by fatolahzadeh** [pmlmodelling/nctoolkit#6] opened 2021-07-06 14:34 UTC
Couldn't install the latest stable version (0.3.5) using conda on Linux (Ubuntu). It keeps installing 0.2.X.

**Comment by r4ecology** [comment] 2021-07-06 14:57
How are you installing it?

Have you tried:
    `conda install nctoolkit=0.3.5`

I believe conda takes a "path of least resistance" approach to installing packages, so it installs the version that makes resolving dependency versions easiest. I've just tried installing nctoolkit it and it went to v0.2.2 because of this.

In fact I've also just tried installing 0.3.5 and it is taking a long time to resolve dependencies. There must be something strange going on with how one of the dependencies pin stuff on conda-forge. In case you don't know, package developers can specify which version(s) of dependencies should  be installed for the conda-forge packages. But this can cause a mess as there can be conflicts. 

nctoolkit only pins xarray to something less than 2 years old. So it's not nctoolkit causing the problem

The easiest way to solve this problem is likely to just install nctoolkit using pypi:

    `conda install cdo`
    `conda install nco`
    `pip install nctoolkit==0.3.5`

That should giving you a working version of nctoolkit.

Let me know if the above fixes the problem. Because the conda problem seems to be caused by pinning in a dependency (and it's impossible to figure out which), it's not clear if I can fix the conda installation directly.

**Comment by fatolahzadeh** [comment] 2021-07-06 15:09
Thank you for the quick reply. I could install it using:

`conda install -c conda-forge nctoolkit=0.3.5
`
It's strange that the command didn't work initially, here's the workaround that potentially fixed it:

1. Created a fresh environment to get rid of previous unsuccessful attempts.
2. Used `conda install -c conda-forge nctoolkit` it installed the 0.2.X version. It took hours.
3. An update command on all the packages in the environment.
4. Another install command forcing the 0.3.5 version.

**Closed** 2021-07-06 15:09 UTC

**Comment by r4ecology** [comment] 2021-07-06 15:12
Thanks. My current approach with conda is to mostly install python packages using pip because it makes resolving dependencies easier. Though there are potential pitfalls with that.
